version: '3'

services:
  postgres:
    image: postgres:16.1-alpine3.19
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    restart: always

  redis:
    image: redis:7.2.3
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: myredispassword
    restart: always

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mymongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mymongopassword
    volumes:
      - mongodb_data:/data/db
    restart: always


#  backend:
#    build:
#      context: ./BackEnd
#    ports:
#      - "5000:5000"

volumes:
  postgres_data:
  mongodb_data:


