version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mymongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mymongopassword
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: myredispassword

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

      frontend:
    image: node:14
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: npm start

  backend:
    image: python:3.8
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    command: python app.py

volumes:
  mongodb_data:
  postgres_data:
